version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "evansims"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "evansims"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (Ghost theme)
  - package-ecosystem: "npm"
    directory: "/ghost-theme"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "evansims"
    labels:
      - "dependencies"
      - "javascript"
      - "ghost-theme"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major Ghost version updates to ensure compatibility
      - dependency-name: "ghost"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all non-major npm updates together
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"