services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ghost
      - activitypub
    networks:
      - ghost-network

  ghost:
    image: ghost:6.0.0-rc.0
    restart: always
    environment:
      # Database configuration
      database__client: ${DATABASE_CLIENT:-mysql}
      database__connection__host: ${DATABASE_HOST:-db}
      database__connection__user: ${DATABASE_USER:-ghost}
      database__connection__password: ${DATABASE_PASSWORD}
      database__connection__database: ${DATABASE_NAME:-ghost}

      # Ghost configuration
      url: ${GHOST_URL:-https://evansims.com}
      NODE_ENV: ${NODE_ENV:-production}

      # Development/debugging
      paths__contentPath: /var/lib/ghost/content

      # Enable ActivityPub (beta feature)
      labs__ActivityPub: ${ENABLE_ACTIVITYPUB:-true}

      # Mail configuration (optional - configure as needed)
      mail__transport: ${MAIL_TRANSPORT:-SMTP}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT:-587}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}

    volumes:
      - ghost_content:/var/lib/ghost/content
      - ./ghost-theme:/var/lib/ghost/content/themes/evansims-theme
      - ./ghost-entrypoint.sh:/usr/local/bin/ghost-entrypoint.sh:ro
      # - ./ghost-redirects.yaml:/tmp/redirects.yaml:ro
    entrypoint: ["/usr/local/bin/ghost-entrypoint.sh"]
    command: ["node", "current/index.js"]
    depends_on:
      - db
      - activitypub
    networks:
      - ghost-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER:-ghost}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME:-ghost}
    volumes:
      - ghost_mysql:/var/lib/mysql
    networks:
      - ghost-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  activitypub:
    image: ghcr.io/tryghost/activitypub:edge
    restart: always
    environment:
      # Database configuration (same as Ghost)
      MYSQL_USER: ${DATABASE_USER:-ghost}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DATABASE_NAME:-ghost}
      
      # ActivityPub configuration
      PORT: 8080
      NODE_ENV: ${NODE_ENV:-production}
      
      # Storage configuration
      LOCAL_STORAGE_PATH: /opt/activitypub/content
      GCP_BUCKET_NAME: local-bucket  # Required even for local storage
      USE_MQ: false  # Disable message queue for simpler setup
      
      # Federation settings
      ALLOW_PRIVATE_ADDRESS: false
      SKIP_SIGNATURE_VERIFICATION: false
      ACTIVITYPUB_COLLECTION_PAGE_SIZE: 20
      
      # Ghost integration
      GHOST_URL: ${GHOST_URL:-https://evansims.com}
      
    volumes:
      - activitypub_content:/opt/activitypub/content
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ghost-network

volumes:
  ghost_content:
  ghost_mysql:
  activitypub_content:
  caddy_data:
  caddy_config:

networks:
  ghost-network:
