name: Ghost Theme Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'ghost-theme/**'
      - '.github/workflows/ghost-theme-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install GScan globally
        run: npm install -g gscan

      - name: Run GScan theme validation
        run: |
          cd ghost-theme
          gscan . --verbose
          
      - name: Check theme structure
        run: |
          cd ghost-theme
          echo "Checking required files..."
          
          # Check for required template files
          for file in index.hbs post.hbs default.hbs package.json; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            else
              echo "✅ Found: $file"
            fi
          done
          
          # Check for built CSS
          if [ ! -f "assets/built/screen.css" ]; then
            echo "⚠️  No built CSS found, attempting to build..."
            mkdir -p assets/built
            cp assets/css/screen.css assets/built/screen.css
          fi
          
          echo "✅ All required files present"

      - name: Validate package.json
        run: |
          cd ghost-theme
          node -e "
          const pkg = require('./package.json');
          const errors = [];
          
          // Check required fields
          if (!pkg.name) errors.push('Missing name');
          if (!pkg.version) errors.push('Missing version');
          if (!pkg.author?.email) errors.push('Missing author.email');
          
          // Check name format
          if (pkg.name && pkg.name !== pkg.name.toLowerCase()) {
            errors.push('Name must be lowercase');
          }
          if (pkg.name && !pkg.name.match(/^[a-z0-9-]+$/)) {
            errors.push('Name must be hyphenated (lowercase letters, numbers, and hyphens only)');
          }
          
          // Check version format
          if (pkg.version && !pkg.version.match(/^\d+\.\d+\.\d+$/)) {
            errors.push('Version must be semver compliant (e.g., 1.0.0)');
          }
          
          if (errors.length > 0) {
            console.error('❌ package.json validation failed:');
            errors.forEach(e => console.error('  - ' + e));
            process.exit(1);
          } else {
            console.log('✅ package.json is valid');
          }
          "

      - name: Create theme zip for artifact
        run: |
          cd ghost-theme
          zip -r ../ghost-theme.zip . -x "*.git*" "node_modules/*" "*.log"

      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghost-theme
          path: ghost-theme.zip
          retention-days: 7

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## Ghost Theme Validation Results\n\n';
            
            if (${{ job.status }} === 'success') {
              comment += '✅ **All theme validation checks passed!**\n\n';
              comment += 'The theme is ready to be deployed to Ghost.';
            } else {
              comment += '❌ **Theme validation failed**\n\n';
              comment += 'Please check the workflow logs for details.';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });